export const FETCH_LOCINFO_REQUEST = 'FETCH_LOCINFO_REQUEST'
export const FETCH_LOCINFO_FAILURE = 'FETCH_LOCINFO_FAILURE'
export const FETCH_LOCINFO_SUCCESS = 'FETCH_LOCINFO_SUCCESS'
export const RESET_INFO = 'RESET_INFO'
