export const FETCH_LOCID_REQUEST = 'FETCH_LOCID_REQUEST'
export const FETCH_LOCID_FAILURE = 'FETCH_LOCID_FAILURE'
export const FETCH_LOCID_SUCCESS = 'FETCH_LOCID_SUCCESS'
export const SET_ID = 'SET_ID'
